### ISSUE TITLE
Reduce Provider Duplication

### ISSUE THREAD

**Issue by cnuss** [saml-to/cli#10]
**Is your feature request related to a problem? Please describe.**
 - Allow variables to be defined at various `permissions.{provider}` level
 - Allow reference to a single provider where variables

**Describe the solution you'd like**
Possible config for this:

```
providers:
  aws:
    entityId: https://signin.aws.amazon.com/saml
    acsUrl: https://signin.aws.amazon.com/saml
    attributes:
      https://aws.amazon.com/SAML/Attributes/RoleSessionName: "<#= user.github.login #>"
      https://aws.amazon.com/SAML/Attributes/SessionDuration: "43200"
      https://aws.amazon.com/SAML/Attributes/Role: "<#= user.selectedRole #>,arn:aws:iam::<$= accountId $>:saml-provider/saml.to"
permissions:
  aws-account1:
    provider: aws # << ADD THIS
    variables: # << ADD THIS
      accountId: "0123456789012"
    roles:
      - name: arn:aws:iam::<$= accountId $>:role/admin
        users:
          github:
            - user1
  aws-account2:
    provider: aws # << ADD THIS
    variables: # << ADD THIS
      accountId: "2109876543210"
    roles:
      - name: arn:aws:iam::<$= accountId $>:role/admin
        users:
          github:
            - user1
```

**Comment by cnuss** [comment]
This has been added. 

Config can now be:

```
variables:
  accountId1: '123456789012'
  accountId2: '210987654321'
providers:
  aws:
    entityId: https://signin.aws.amazon.com/saml
    acsUrl: https://signin.aws.amazon.com/saml
    attributes:
      https://aws.amazon.com/SAML/Attributes/RoleSessionName: "<#= user.github.login #>"
      https://aws.amazon.com/SAML/Attributes/SessionDuration: "43200"
      https://aws.amazon.com/SAML/Attributes/Role: "<#= user.selectedRole #>,<#= provider.variables.providerArn #>"
permissions:
  aws:
    roles:
      - name: arn:aws:iam::<$= accountId1 $>:role/admin
        provider:
          variables:
            providerArn: arn:aws:iam::<$= accountId1 $>:saml-provider/saml.to
        users:
          github:
            - cnuss
      - name: arn:aws:iam::<$= accountId2 $>:role/admin
        provider:
          variables:
            providerArn: arn:aws:iam::<$= accountId2 $>:saml-provider/saml.to
```
