### ISSUE TITLE
Variables at role level

### ISSUE THREAD

**Issue by cnuss** [saml-to/cli#25]
Allow the ability have in config:

```
---
# Config Reference: 
# https://docs.saml.to/configuration/reference
version: '20220101'
variables:
  awsAccountId: '580360238192'
  sessionDuration: '3600'
providers:
  aws:
    entityId: https://signin.aws.amazon.com/saml
    acsUrl: https://signin.aws.amazon.com/saml
    attributes:
      https://aws.amazon.com/SAML/Attributes/RoleSessionName: '<#= user.github.login #>'
      https://aws.amazon.com/SAML/Attributes/SessionDuration: '<$= sessionDuration $>'
      https://aws.amazon.com/SAML/Attributes/Role: '<#= user.selectedRole #>,arn:aws:iam::<$= awsAccountId $>:saml-provider/saml.to'
permissions:
  aws:
    roles:
      - name: arn:aws:iam::<$= awsAccountId $>:role/short-duration
        users:
          github:
            - cnuss
     - name: arn:aws:iam::<$= awsAccountId $>:role/long-duration
        variables:
          sessionDuration: '43200'
        users:
          github:
            - cnuss
```
