### ISSUE TITLE
Support for GitHub teams in saml-to.yml

### ISSUE THREAD

**Issue by cnuss** [saml-to/cli#9]
**Is your feature request related to a problem? Please describe.**
Allow support for referencing GitHub teams in config

**Describe the solution you'd like**
Currently:

```
permissions:
  aws:
    roles:
      - name: arn:aws:iam::<$= awsAccountId $>:role/admin
        users:
          github:
            - user1
            - user2
            - user3
```

It'd be great to:

Put user1, user2, and user3 on a `team1` in an organization, then do config like:

```
permissions:
  aws:
    roles:
      - name: arn:aws:iam::<$= awsAccountId $>:role/admin
        teams:
          github:
            - team1
```
